### ISSUE TITLE
get back to work on this !!

### ISSUE THREAD

**Issue by aaannndddyyy** [Quoturnix/ProjectTox-Core#7]
I think you have great ideas and it would be a shame if they are lost and tox moves on into another direction and later becomes totally incompatible. 

We need good groupchat, that workd on udp and tcp-only, 
that has autorejoin if ocnenction is lost, is persistent over restarts (just liek a friend stays in my friend list, the chat should stay and when I restart client chat should be there, unless I left it. 
There should be both: joining a chat via a chat id, or via drag and drop a friend into it.
And it should be super flexible: 
1) founder and moderators (moderated chat)
2) no moderators (either moderated by founder or temporarily anarchic)
3) not even a recoginizable founder. (permanently anarchic chat, each user can only locally ignore) 

IMHO, the new groupchats should be as flexible as possible. I.e. not necesarily all groupchats have moderators, but they can have. So unlike now, operators are not impossible, but neither mandatory, such that totally opless groupchats with the option for every user to mute other group memeber's audio for them locally and to ignore their text messages are possible too. Both are LOCAL decisions by each user for their OWN user experience, not for others. These options should also exist in non-anarchic chats. So that if an op does not mute one member's audio or /mute his text, I can still /ignore that user locally if I'm not pleased by his contributions.

On https://github.com/Quoturnix/ProjectTox-Core/wiki/Group-Chat you write about the founder's key: "the public part of which is considered the chatid. ", and further down "[...] which potentially gives us possibility to move towards less founder-oriented model." I suggest not using the founder's key as chatid, but a hash of the unchangeable chat manifest.

The manifest would be the chat, i.e. all decisive characteristics of the chat are store in the manifest. It only contains unchanging propperties. If the chat is moderated, its founder's long time pubkey would be in the manifest. If it is anarchic, no founder would be present at all. So that in a popular anarchic channel the founder cannot later change his mind and take over the anarchic channel anymore. Anarchic is anarchic and remains so. Therefore no founder at all. chatid = hash of chat manifest. This would guarantee the possibility of founderless groupchats. (What else guarantees you that a popular anarchic chat does not get taken over by its founder who then turns it into moderated?) And still it would be equally possible to have founders and operators. You lookup a peer being in the chat with a certain chat id and simply get the manifest from him. If he tampers with it, its cryptographic hash does not match the chat id, and the peers and manifest are discarded. Otherwise manifest is read and client acts accordingly; like eg. requesting list of operators (checks it since those need to be signed by founder or other operator/moderator/admin) and then request from those lists of banned peers etc. All properties that can change should be done with different certificates signed by the founder or by op's who in turn got approved by founder (and who can also be revoked - then all op actions from a revoked op would be ignored by the other users' clients).

Apart from operators and (GUARANTEED PERMANENTLY) operatorless chats, there should also be the possibility to pm single group members and to send them a friend request (for convenience automated through pm).

**Comment by alnf** [comment]
We got back

**Comment by aaannndddyyy** [comment]
yay!
I am looking forward to be using it soon.
